apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginxs.custom.config
spec:
  group: custom.config
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: nginxs
    # singular name to be used as an alias on the CLI and for display
    singular: nginx
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Nginx
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - ngx
  # either Namespaced or Cluster
  scope: Namespaced
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                worker_processes:
                  type: integer
              required: ["worker_processes"]
          required: [ "spec" ]